### ISSUE TITLE
Implement api-var-test QueueTest testing

### ISSUE THREAD

**Issue by tyler-gilbert** [StratifyLabs/sostest#25]
This include the api, performance and stress.

## API Test

The API test should test all the code of the API. It should force all the errors and see if anything unexpected happens. The API should verify that all documentation is correct and accurate.

## Performance Test

The performance test should just an identical set of operations thousands of times. It should run the same operations every time.

## Stress Test

The stress test should push the system to its limit and use thousands of random cases to ensure nothing fails.

**Comment by shomagan** [comment]
I left the first pull request for the api test,(https://github.com/StratifyLabs/sostest/pull/26)
move in this direction?
If yes then on Monday(09.04.2018) there will be tests for queues

**Comment by tyler-gilbert** [comment]
@shomagan 

These tests look great please continue.

I am going to make one change to the Test.hpp API.

```
void Test::print_case_message(const char * key, const char * fmt, ...);
```

is going to become 
```
void Test::print_case_message_with_key(const char * key, const char * fmt, ...);
```

So please use this function for all the testing outputs:
```
void Test::print_case_message(const char * fmt, ...);
```

You will just need to delete the first argument of usages of print_case_message(). The key for the message will be generated automatically.

Thanks!

**Comment by tyler-gilbert** [comment]
For example, change line 54 of StringTest.cpp to this:

```
        print_case_message("Failed: %s: %d", __PRETTY_FUNCTION__, __LINE__);
```

Every failure can be the same message to make it simple

**Comment by shomagan** [comment]
in pull request https://github.com/StratifyLabs/sostest/pull/28, 
!!!problem in the test "Stress", it is identical "Performance" but have little bit more cycles,
 and he freezes
