### ISSUE TITLE
More String::insert and String::erase API test cases

### ISSUE THREAD

**Issue by tyler-gilbert** [StratifyLabs/sostest#31]

**Comment by tyler-gilbert** [comment]
@shomagan Can you add a few more insert and erase cases?

I fixed the failures with String and committed to StratifyAPI.

Also the queue stress test fails because it runs out of memory:

https://www.dropbox.com/s/vq6s812tcirj2bv/sos-heap-stack-collision.mov?dl=0

**Comment by shomagan** [comment]
i add some test for insert and erase, and  saw some mistaken 
1. if length after insert near 55 
2. insert and erase working with some string, but in performance test failed

https://github.com/StratifyLabs/sostest/pull/35

**Comment by tyler-gilbert** [comment]
@shomagan I fixed the issue with insert().

You will need to pull, build and install the StratifyAPI library again.
