### ISSUE TITLE
sys::Mutex doesn't like 3 threads

### ISSUE THREAD

**Issue by tyler-gilbert** [StratifyLabs/sostest#54]
@shomagan I ran the sys mutex stress test. The OS just bounces back and forth between 2 threads and never yields the mutex to the first thread. I will add an issue to the StratifyOS to fix this but for now if you do Timer::wait_microseconds() for a longer period of time while the mutex is unlocked, the first thread should have a chance to grab it.

The tests are looking great so far. Keep up the good work.

**Comment by tyler-gilbert** [comment]
https://github.com/StratifyLabs/StratifyOS/issues/139

**Comment by shomagan** [comment]
Good day, where I can read the information about sheduling, and how switching occurs . if use yield will it go to another process? with more low priority. Use Timer::wait, runs the sheduller handling?and how does an external  shedulling handling work(every time interval?) with out internal yield.

**Comment by tyler-gilbert** [comment]
I just added some details here:

https://stratifylabs.co/StratifyAPI/html/classsys_1_1_sched.html
